version: '3.8'

services:
  products:
    build:
      context: ./products
    ports:
      - "3001:3001"
    networks:
      - app-network

  orders:
    build:
      context: ./orders
    ports:
      - "3002:3002"
    depends_on:
      - products
      - db
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=ecommerce

  payments:
    build:
      context: ./payments
    ports:
      - "3003:3003"
    depends_on:
      - orders
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"  # Mapeia 3306 do container para 3307 no host
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
